void api_putchar(int c);
void api_putstr(unsigned char *s);
void api_putnstr(unsigned char *s, int l);
void api_end(void);
int api_openwin(unsigned char *buf, int xsize, int ysize, int col_inv, unsigned char *title);
void api_putstrwin(int win, int x, int y, int col, int len, unsigned char *str);
void api_boxfillwin(int win, int x0, int y0, int x1, int y1, int col);
void api_initmalloc(void);
unsigned char *api_malloc(int size);
void api_free(char *addr, int size);
void api_point(int win, int x, int y, int col);
void api_refreshwin(int win, int x0, int y0, int x1, int y1);
void api_linewin(int win, int x0, int y0, int x1, int y1, int col);
void api_closewin(int win);
int api_getkey(int mode);
int api_alloctimer(void);
void api_inittimer(int timer, int data);
void api_settimer(int timer, int time);
void api_freetimer(int timer);
void api_beep(int tone);
int api_fopen(unsigned char *fname);
void api_fclose(int fhandle);
void api_fseek(int fhandle, int offset, int mode);
int api_fsize(int fhandle, int mode);
int api_fread(unsigned char *buf, int maxsize, int fhandle);
int api_cmdline(unsigned char *buf, int maxsize);
